name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0
      - name: Run TFLint
        run: tflint --recursive
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Run Terratest
        run: |
          go test -v ./tests

        if: github.event_name == 'push'
      - name: Update Badge
        run: |
          echo "[![Terraform CI](https://github.com/theoneglobal/azure-devops-bootstrap/workflows/Terraform%20CI/badge.svg)](https://github.com/theoneglobal/azure-devops-bootstrap/actions)" > badge.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add badge.md
          git commit -m "Update Terraform CI badge" || true
          git push
